### ISSUE TITLE
Typo and other issues

### ISSUE THREAD

**Issue by Nealsen** [magpiexyz/subgraph_public#1]
Path: eigenpie/CurveLP.ts

- The variable 'storedBalabce' appears to be a typo and should likely be 'storedBalance'

- Division by Zero: In the line status.mlrtPerShare = status.token0Balance.times(ETHER_ONE).div(status.totalSupply), there's a division by status.totalSupply. If status.totalSupply is zero (which can happen, especially in early stages or if all liquidity is removed), this will result in a division by zero error. It's important to handle this case, perhaps by setting status.mlrtPerShare to zero or another default value when status.totalSupply is zero.

- When calculating status.mlrtPerShare, consider the potential for precision loss due to integer division. If ETHER_ONE and totalSupply are both large numbers, the division might lead to rounding errors. Depending on the use case, it might be necessary to handle such precision issues.

**Comment by freejerry** [comment]
Thank you for your submission. You're correct that a Division by Zero error could occur under certain conditions, though it does not affect the point calculations. To clarify the computational logic further, we have completely refactored all the code.

**Comment by Nealsen** [comment]
Thank you
