### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by Nealsen** [magpiexyz/subgraph_public#2]
Path: eigenpie/CurveLPTransfer.ts

what happens if 'curveLPReceipt.get_balances()' returns an array with fewer than two elements or if any external calls fail?
Consider adding try-catch blocks or validation checks

**Comment by freejerry** [comment]
Thank you for your feedback. According to the contract's design, the code section you mentioned is functioning as expected. We've thoroughly evaluated these scenarios to ensure the contract's integrity. While we appreciate your suggestions, the current implementation aligns with our design goals. We'll keep your feedback in mind for future updates. Thanks for helping us improve our project.
