### ISSUE TITLE
Potential Logic Issue in loadOrCreateReferralData Function

### ISSUE THREAD

**Issue by matomoniwano** [magpiexyz/subgraph_public#3]
[https://github.com/magpiexyz/subgraph_public/blob/3ce589c2d18e6a7170d2c864592f5b0611b653e2/eigenpie/entity-operations.ts#L20](https://github.com/magpiexyz/subgraph_public/blob/3ce589c2d18e6a7170d2c864592f5b0611b653e2/eigenpie/entity-operations.ts#L20)

Description:
Hey folks, I noticed in the loadOrCreateReferralData function. It seems there's a chance for things to get a bit wonky when figuring out who referred whom. 

Issue Details:
When you call loadOrCreateReferralData and pass in referrerAddr as ADDRESS_ZERO, it kind of assumes the user referred themselves. Now, that's not always what we want?This could lead to some mix-ups in the referral system.

Proposed Solution:
Here's my two cents: We need to tweak how we handle cases where referrerAddr is ADDRESS_ZERO. Instead of automatically pointing the finger back at the user, we should probably handle it differently. Maybe set the referrer to null or use a default referrer?

for instance, add   
`referrer = null` 

before referralGroup assignment

**Comment by freejerry** [comment]
Thank you for your submission. You are correct about the mechanism in the loadOrCreateReferralData function being designed that way. However, in the interest of clarity and to ensure the logic is more straightforward, we have already undertaken a comprehensive refactoring of all the code related to this functionality.
