### ISSUE TITLE
"Bug Report: Typos and Error Handling in CurveLP.ts

### ISSUE THREAD

**Issue by moufidoff** [magpiexyz/subgraph_public#4]
Typo in the variable storedBalabce: There appears to be a typo in the variable name storedBalabce. It's likely that it should be storedBalance.

Checking for the presence of the variable status before its usage: Before accessing the properties of the status object, it would be prudent to check if it is defined to avoid errors. Although the current code creates a new mlrtLiquidityStatus object if it doesn't exist, an explicit check could enhance the readability and robustness of the code.

Handling potential errors in the updateLiquidity function: This function makes calls to the CurveLP.bind and mlrtLiquidityStatus.load functions without verifying if these operations can fail. It could be beneficial to add error handling mechanisms to address cases where these operations do not succeed.

**Comment by freejerry** [comment]
Thank you for your feedback. We acknowledge the typo, the need for a status check, and the addition of error handling. Corrections will be made accordingly.
