### ISSUE TITLE
Error Handling and Naming Consistency in eigenpie-config.ts

### ISSUE THREAD

**Issue by moufidoff** [magpiexyz/subgraph_public#5]
Naming consistency: Ensure consistency in variable naming throughout the codebase. For instance, there's a variable named userPrevTvl, consider making it userPreviousTvl for clarity.

Error Handling: Similar to the previous file, this script doesn't include error handling for various function calls, such as try_exchangeRateToNative. It's crucial to handle potential errors to maintain the stability and reliability of the code.

**Comment by freejerry** [comment]
Thanks for the issues submission

On the aspect of naming consistency: We appreciate the insights regarding variable naming within our codebase. Rest assured, we have conducted a comprehensive refactor to ensure our naming conventions are optimized for clarity.

As for error handling: Acknowledging the importance of robust processes, we have implemented a refactor that addresses this area, enhancing the code's stability and reliability.
