### ISSUE TITLE
Group TVL Adjustment Logic

### ISSUE THREAD

**Issue by Nealsen** [magpiexyz/subgraph_public#6]
Path: eigenpie/MLRT.ts

TVLs are adjusted based on whether **transferFromGroup.id** and **transferToGroup.id** are equal. The current setup decreases the TVL of the sender's group and increases that of the recipient's group, which might not always be the desired outcome.

**Comment by freejerry** [comment]
In response to the report regarding the behavior within the eigenpie/MLRT.ts file, specifically concerning how TVLs are adjusted based on the equality of transferFromGroup.id and transferToGroup.id: The transfer functionality has undergone thorough testing, and at this point, no edge cases have been identified that would result in exceptions to the described behavior.
