### ISSUE TITLE
BUG report: Deposited number on restake page is not the same with dashboard page. 

### ISSUE THREAD

**Issue by Rogerluoluo** [magpiexyz/subgraph_public#7]
Deposited number on restake page is not the same with dashboard page.  I swap some msteth from curve, so the bug is there. Need to fix.
![微信图片_20240227220229](https://github.com/magpiexyz/subgraph_public/assets/161480995/57566350-01a5-4e8f-a632-b870e6041fd4)
![微信图片_20240227220237](https://github.com/magpiexyz/subgraph_public/assets/161480995/3b4d99cb-3b31-4e9e-87cc-c397031ae7fd)

**Comment by freejerry** [comment]
Thank you for submitting this issue. The discrepancy between the deposited number on the restake page and the dashboard page has been confirmed to be fixed in the new version of the subgraph.
